apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stateful-web
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: public
  tls:
    - hosts:
        - stateful.kennedn.com
      secretName: stateful-web-tls
  rules:
    - host: stateful.kennedn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stateful-web
                port:
                  number: 80
