resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

namespace: default

commonLabels:
    app: stateful-web

secretGenerator:
- name: stateful-web-basic-auth
  behavior: create
  options:
    disableNameSuffixHash: true
  files:
  - auth=config/htpasswd
